config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.home_view, name='home'), 
    path('sobre', views.sobre_view, name='sobre'),
    path('projetos', views.projetos_view, name='projetos'),
    path('web', views.web_view, name='web'),
    path('blog', views.blog_view, name='blog'),
    path('blog_novo/', views.nova_tarefa_view, name='blog_novo'),
    path('blog_editar/<int:portfolio_id>', views.edita_tarefa_view, name='blog_editar'),
    path('apaga/<int:portfolio_id>', views.apaga_tarefa_view, name='apaga'),
    path('contactos', views.contactos_view, name='contactos'),
    path('quizz', views.quizz, name='quizz'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout')
]

portfolio/models.py
from email.policy import default
from django.db import models

class New(models.Model):
    titulo = models.CharField(max_length=50)
    imagem = models.ImageField(upload_to="static/portfolio/images", blank=True)
    autor = models.CharField(max_length=40)
    data = models.DateTimeField(auto_now_add=True)
    descricao = models.CharField(max_length=500)
    link = models.CharField(max_length=1000)

    def __str__(self):
          return self.titulo[:50]

class Person(models.Model):
    nome = models.CharField(max_length=60)
    linklusofona = models.CharField(max_length=1000, default='1')
    linklinkedin = models.CharField(max_length=1000, default='1')

    def __str__(self):
          return self.nome[:50]

class Tecnologia(models.Model):
    nome = models.CharField(max_length=30)
    acronimo = models.CharField(max_length=10, blank=True)
    ano = models.IntegerField()
    criador = models.CharField(max_length=40)
    logotipo = models.ImageField(upload_to="static/portfolio/images")
    link = models.CharField(max_length=500)
    descricao = models.TextField(max_length=1000)
    existente = models.BooleanField(default=False)

    def __str__(self):
          return self.nome[:50]

class Education(models.Model):
    formacao = models.CharField(max_length=70)
    curso = models.CharField(max_length=60)
    topicos = models.CharField(max_length=500, default='1')
    local = models.CharField(max_length=50)
    periodo = models.CharField(max_length=50)
    imagem = models.ImageField(upload_to="static/portfolio/images", default='1')
    logotipo = models.ImageField(upload_to="static/portfolio/images")

    def __str__(self):
          return self.formacao[:50]

class Project(models.Model):
    titulo = models.CharField(max_length=50)
    imagem = models.ImageField(upload_to="static/portfolio/images")
    tecnologia = models.ManyToManyField(Tecnologia)
    participantes = models.CharField(max_length=100)
    cadeira = models.CharField(max_length=40)
    ano = models.IntegerField()
    descricao = models.CharField(max_length=500)
    linkgithub = models.CharField(max_length=1000, blank=True)

    def __str__(self):
          return self.titulo[:50]

class Chair(models.Model):
    nome = models.CharField(max_length=60)
    ano = models.IntegerField()
    semestre = models.IntegerField()
    descricao = models.TextField(max_length=1000)
    ects = models.IntegerField()
    ano_letivo = models.CharField(max_length=20, default='1')
    topicos_abordados = models.CharField(max_length=1000, default='1')
    ranking = models.IntegerField()
    docente_teorica = models.ForeignKey(Person, on_delete=models.CASCADE, default='1')
    docentes_praticas = models.ManyToManyField(Person, related_name='professor_pratica')
    link_cadeira = models.CharField(max_length=1000, default='1')
    linguagens = models.ManyToManyField(Tecnologia, blank=True)
    projetos = models.ManyToManyField(Project, blank=True)

    def __str__(self):
          return self.nome[:50]

class Achivement(models.Model):
    titulo = models.CharField(max_length=70, default='1')
    descricao = models.CharField(max_length=100, default='1')
    projetos = models.ManyToManyField(Project, blank=True)
    cadeira = models.CharField(max_length=40, default='1')

    def __str__(self):
          return self.titulo[:50]

class Noticia(models.Model):
    titulo = models.CharField(max_length=80)
    texto = models.TextField(max_length=1000)
    imagem = models.ImageField(upload_to="static/portfolio/images")
    link = models.CharField(max_length=1000)
    
    def __str__(self):
          return self.titulo[:50]

class Lab(models.Model):
    titulo = models.CharField(max_length=70)
    descricao = models.TextField(max_length=1000)
    link = models.CharField(max_length=1000)

    def __str__(self):
          return self.titulo[:50]

class TFC(models.Model):
    titulo = models.CharField(max_length=50)
    sumario = models.TextField(max_length=1000)
    linkGitHub = models.CharField(max_length=1000)
    linkYoutube = models.CharField(max_length=1000)
    linkRelatorio = models.CharField(max_length=1000)
    ano = models.IntegerField()
    orientador = models.ManyToManyField(Person)
    autor = models.CharField(max_length=70)
    imagem = models.ImageField(upload_to="static/portfolio/images", null=True, blank=True)

    def __str__(self):
          return self.titulo[:50]

class PontuacaoQuizz(models.Model):     
    nome = models.CharField(max_length=20)    
    apelido = models.CharField(max_length=20)     
    pontuacao = models.IntegerField()

    def __str__(self):
        return self.nome[:50]

# Create your models here.

portfolio/forms.py
from django import forms
from django.forms import ModelForm
from .models import New

class NewForm(ModelForm):
    class Meta:
        model = New
        fields = '__all__'
    # inserção de classes CSS para formatação de cada campo do formulário
        widgets = {
            'autor': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'autor'}),
            'data': forms.DateInput(attrs={'class': 'form-control','placeholder': 'Select a date','type': 'date'}),
            'titulo': forms.TextInput(attrs={'class': 'form-control', 'placeholder' : 'titulo'}),
            'link': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'link'}),
            'descricao': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'descricao'}),
        }
    # texto a exibir junto à janela de inserção
        labels = {
            'autor': 'Autor',
            'data': 'Data',
            'titulo': 'Título',
            'link': 'Link',
            'descricao': 'Descrição',
        }

portfolio/views.py
from .models import *

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .forms import NewForm

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


from matplotlib import pyplot as plt
# Create your views here.

def layout_view(request):
    return render(request, 'portfolio/layout.html' )

def home_view(request):
    return render(request, 'portfolio/home.html' )

def sobre_view(request):
    context = {'chairs': Chair.objects.all(), 'educations': Education.objects.all()}
    return render(request, 'portfolio/sobre.html', context)

def projetos_view(request):
    context = {'projetos': Project.objects.all(), 'tfcs': TFC.objects.all()}
    return render(request, 'portfolio/projetos.html', context)

def web_view(request):
    context = {'noticias': Noticia.objects.all(), 'tecs': Tecnologia.objects.all(), 'tecs_usadas': Tecnologia.objects.all().filter(existente=True), 'labs': Lab.objects.all()}
    return render(request, 'portfolio/web.html', context)

def blog_view(request):
    context = {'news': New.objects.all()}
    return render(request, 'portfolio/blog.html', context)

def nova_tarefa_view(request):
    form = NewForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:blog'))
    context = {'form': form}
    return render(request, 'portfolio/blog_novo.html', context)

@login_required
def edita_tarefa_view(request, portfolio_id):
    tarefa = New.objects.get(id=portfolio_id)
    form = NewForm(request.POST or None, instance=tarefa)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:blog'))
    context = {'form': form, 'portfolio_id': portfolio_id}
    return render(request, 'portfolio/blog_editar.html', context)

def apaga_tarefa_view(request, portfolio_id):
    New.objects.get(id=portfolio_id).delete()
    return HttpResponseRedirect(reverse('portfolio:blog'))

def sobre_este_view(request):
    return render(request, 'portfolio/sobre_este.html')

def contactos_view(request):
    return render(request, 'portfolio/contactos.html' )

def perguntas_quizz(request):
    score = 0
    nome = request.POST['nome']
    apelido = request.POST['apelido']
    Django = request.POST['Django']
    css = request.POST['CSS']
    servidor = request.POST['Heroku']
    autor = request.POST['Brendan Eich']
    if Django == "Django" :
        score += 10
    if css == "CSS" :
        score += 10
    if servidor == "Heroku" :
        score += 15
    if autor == "Brendan Eich" :
        score += 15
    return score

def desenha_grafico_resultados():
    participantes = sorted(PontuacaoQuizz.objects.all(), key=lambda t: t.pontuacao, reverse=True)     
    nomes = []     
    pontuacoes = []     
    for pt in participantes:         
        nomes.append(pt.nome +" "+pt.apelido)         
        pontuacoes.append(pt.pontuacao)     
        plt.barh(nomes, pontuacoes)     
        plt.savefig("portfolio/static/portfolio/images/grafico.png", bbox_inches='tight') 

def quizz(request):
    if request.method == 'POST':
        n = request.POST['nome']
        a = request.POST['apelido']
        p = perguntas_quizz(request)
        r = PontuacaoQuizz(nome=n, apelido=a, pontuacao=p)
        r.save()
    context = {
    'pontuacao': p
    }
    context = {
        'pontuacao': p,
        'labs': Lab.objects.all(),
        'tecs': Tecnologia.objects.all(),
    }
    desenha_grafico_resultados()
    return render(request,'portfolio/web.html', context)

def login_view(request):
    if request.method == "POST":
        nome_login = request.POST.get('username')
        password_login = request.POST.get('password')
        utilizador = authenticate(request, username=nome_login, password=password_login)

        if utilizador is not None:
            login(request, utilizador)
            context = {'post': New.objects.all(),}
            return render(request, 'portfolio/blog.html', context)
        else:
            return render(
                request, 'portfolio/login.html',
                {'message': "Credenciais Invalidas"}
            )

    return render(request, 'portfolio/login.html')

def logout_view(request):
    logout(request)
    return render(request, 'portfolio/home.html')

portfolio/templates/portfolio/blog.html
<!-- home.html -->

{% extends 'portfolio/layout.html' %}
{% load static %}
{% block link %}
<link rel="stylesheet" href="{% static 'portfolio/css/estilos.css' %}">
{% endblock %}

{% block main %}
    <div class="container">
        {% for new in news %}
            <div>
                <br>
                <h2>{{new.titulo}}</h2><br>
                <img src="{{new.imagem.url}}" width="200">
                <p><b>Autor: </b>{{new.autor}}</p>
                <br>
                <p>{{new.descricao}}</p><br>
                <button><a href="{{new.link}}">{{new.link}}</a></button>
                <!--<p>{{new.data}}</p>-->
                {% if user.is_authenticated %}
                <button class="edit-btn"><a href="{% url 'portfolio:blog_editar' new.id %}">Editar</a></button>
                {% endif %}
            </div>
        {% endfor %}
    </div>
    <button class="new-btn"><a href="{% url 'portfolio:blog_novo' %}" >+ Nova New</a></button>
{% endblock %}

portfolio/templates/portfolio/blog_editar.html
<!-- home.html -->
   
{% extends 'portfolio/layout.html' %}

{% block main %}
<h3>Blog</h3>
    <form action="{% url 'portfolio:blog_editar' portfolio_id %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'portfolio:home' %}" role="button" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar" class="btn btn-success" >
        <a href="{% url 'portfolio:apaga' portfolio_id %}" role="button" class="btn btn-danger">Apagar</a>
    </form>
{% endblock %}

portfolio/templates/portfolio/blog_novo.html
   
{% extends 'portfolio/layout.html' %}

{% block main %}
<h3>Novo Blog</h3>

    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'portfolio:home' %}" role="button" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar" class="btn btn-success" >
    </form>

{% endblock %}

portfolio/templates/portfolio/contactos.html
<!-- contactos.html -->

{% extends 'portfolio/layout.html' %}
{% load static %}
{% block link %}
<link rel="stylesheet" href="{% static 'portfolio/css/estilos.css' %}">
{% endblock %}

{% block main %}
    <div class="contactos">
        <div class="contacto_nome"><p><b>Nome:</b>  João Miguel Isidro Antas</p></div>
        <div class="contacto_loc"><p><b>Localização:</b> Lisboa - Portugal</p></div>
        <div class="contacto_email1"><p><b>Email Institucional:</b> a22002629@alunos.ulht.pt</p></div>
        <div class="contacto_email2"><p><b>Email Pessoal:</b> joaoisidroantas@gmail.com</p></div>
        <div class="contacto_tel"><p><b>Telemóvel:</b> +351 960 301 870</p></div>

        <div class="icons">
                <a href="https://www.linkedin.com/in/joaoantas05/"> {% load static %} <img src="{% static 'portfolio/images/linkedin.png' %}" width="35"></a>
                <a href="https://github.com/joaoantas22002629/pw-labs-joaoantas-a22002629"> {% load static %} <img src="{% static 'portfolio/images/github.png' %}" width="35"></a>
                <a href="mailto:joaoisidroantas@gmail.com"> {% load static %} <img src="{% static 'portfolio/images/gmail.png' %}" width="35"></a>
        </div>
    </div>
{% endblock %}

portfolio/templates/portfolio/home.html
<!-- home.html -->

{% extends 'portfolio/layout.html' %}
{% load static %}
{% block link %}
<link rel="stylesheet" href="{% static 'portfolio/css/estilos.css' %}">
{% endblock %}

{% block main %}
    <div class="inicio">
        <div class="texto">
            <div>
                <p>Olá, Bem vindo!</p>
                <p>Sou o João</p>
                <p>Estudante de Engenharia Informática</p>
                <a href="{% url 'portfolio:sobre' %}" class="about">Sobre mim</a>
                <!--
                <a href="https://www.linkedin.com/in/joaoantas05/"> {% load static %} <img src="{% static 'portfolio/images/linkedin.png' %}" width="35"></a>
                <a href="https://github.com/joaoantas22002629/pw-labs-joaoantas-a22002629"> {% load static %} <img src="{% static 'portfolio/images/github.png' %}" width="35"></a>
                <a href="mailto:joaoisidroantas@gmail.com"> {% load static %} <img src="{% static 'portfolio/images/gmail.png' %}" width="35"></a>
                -->
            </div>
        </div> 
        <div class="dados">
            {% load static %}
            <img src="{% static 'portfolio/images/foto.png' %}" width="450">
        </div>
    </div>

    <div class="carta" id="carta">
        {% load static %}
        <img src="{% static 'portfolio/images/lusofona.jpg' %}" width="100%">
        <article>
            <p>
                Sou estudante do segundo ano do curso de  Engenharia Informática, tenho muita vontade de aprender com os outros, 
                contribuir com ideias e compartilhar experiências, ampliando conhecimentos e horizontes nas áreas das novas tecnologias. 
                Ao longo da minha formação, e de forma a torná-la proveitosa, desenvolvi competências informáticas recorrendo também à auto pesquisa de 
                novas ferramentas de trabalho, de forma a exponenciar a capacidade de adaptação a diferentes áreas. É minha a intenção de, futuramente, 
                complementar a minha formação inicial numa área de especialização, provavelmente em segurança informática pois revela-se uma área bastante 
                apelativa ao trabalho que pretendo desenvolver.
            </p>
        </article>
    </div>

    <div class="api">
        <div>
        <p id="tempoMin"> Temperatura Mínima: </p>
        <p id="tempoMax"> Temperatura Máxima: </p>
        <p id="classWindSpeed"> Humidade: </p>
        </div>
    </div>

    <script>
      document.addEventListener('DOMContentLoaded', function() {
      fetch('https://api.ipma.pt/open-data/forecast/meteorology/cities/daily/1110600.json')// envia GET request ao URL
      .then(response => response.json()) // Põe a resposta no formato json
      .then(data =>{
        let tempoMin = data.data[0].tMin
        document.querySelector('#tempoMin').append(tempoMin);
        let tempoMax = data.data[0].tMax
        document.querySelector('#tempoMax').append(tempoMax);
        let classWindSpeed = data.data[0].classWindSpeed
        document.querySelector('#classWindSpeed').append(classWindSpeed);
      } ); // Põe os dados na consola
     });

     function carbon(distance){
            const options = {
            method: 'GET',
            headers: {
                'X-RapidAPI-Key': '6287c1cb65msh3b631dd5192f66bp1a0bcajsn97a0456e26b4',
                'X-RapidAPI-Host': 'carbonfootprint1.p.rapidapi.com'
            }
            };

            fetch('https://carbonfootprint1.p.rapidapi.com/CarbonFootprintFromCarTravel?distance='+String(distance)+'&vehicle=SmallDieselCar', options)
                .then(response => response.json())
                .then(data=>
                    {
                      document.getElementById('result').innerHTML = String("Pegada de corbono por distância percorrida por um automóvel" + " - ") + String(data.carbonEquivalent) + String("Kg");
                    }
                   );
        }
    </script>

    <div class="nova_api">
        <div>
            <p id="result">Pegada de corbono por distância percorrida por um automóvel.</p>
            <input type="text" id="distancia">
            <button onclick="carbon(document.getElementById('distancia').value)">calcula</button>
        </div>
    </div>

{% endblock %}

portfolio/templates/portfolio/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Projeto Web</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'portfolio/css/estilos.css' %}">
    <link rel="icon" href="{% static 'portfolio/images/icon.png' %}">
    {% block link %}    
    {% endblock %}
</head>

<body style="background-color:rgb(195, 246, 233)" onload="tictac();">
    <header>
        <div><a href="{% url 'portfolio:home' %}" class="name">João Antas</a></div>
            <nav>
                <a href="{% url 'portfolio:home' %}">Home</a>      
                <a href="{% url 'portfolio:sobre' %}">Sobre mim</a>          
                <a href="{% url 'portfolio:projetos' %}">Projetos</a>  
                <a href="{% url 'portfolio:web' %}">Web</a> 
                <a href="{% url 'portfolio:blog' %}">Blog</a>
                <a href="{% url 'portfolio:contactos' %}">Contactos</a>  
            </nav>

        {% if not request.user.is_authenticated %}
        <div class="login"><a href="{% url 'portfolio:login' %}">Login</a></div>
        {% endif %}

        {% if request.user.is_authenticated %}
        <div class="login"><a href="{% url 'portfolio:logout' %}">Logout</a></div>
        {% endif %}

         <div class="botao_cv"><a href="{% static 'portfolio/images/cv.png' %}" class="curriculo" download>Download CV</a></div>
    </header>

    <main>
        {% block main %}
        {% endblock main %}
    </main>
      <script>
      function tictac() {
        var myDate = new Date();
        var day = myDate.getDate();
        var month = myDate.getMonth();
        var monthArray = ['Janeiro','Fevereiro','Marco','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro']
        var year = myDate.getYear();
        if (year < 1000) {
          year += 1900;
        }
        var currentTime = new Date();
        var hours = currentTime.getHours();
        var minutes = currentTime.getMinutes();
        var seconds = currentTime.getSeconds();

        if (hours == 24) {
          hours = 0;
        } else if (hours > 12) {
          hours = hours - 0;
        }

        if (hours < 10) {
          hours = "0" + hours;
        }
        if (minutes < 10) {
          minutes = "0" + minutes;
        }
        if (seconds < 10) {
          seconds = "0" + seconds;
        }

        var clock = document.getElementById("relogio");
        clock.textContent = "" + day + " " + monthArray[month] + " " + year + " | " + hours + ":" + minutes + ":" + seconds;
        clock.innerText = "" + day + " " + monthArray[month] + " " + year + " | " + hours + ":" + minutes + ":" + seconds;

        setTimeout("tictac()", 1000)
      }
      tictac();
    </script>
    <footer>
        <div align="center"> <a href="https://www.ulusofona.pt"><img src="{% static 'portfolio/images/logo_ulht.png' %}" width="60"></a>Programação Web | Universidade Lusófona de Humanidades e Tecnologias | 2022  <p id= "relogio"></p></div>
    </footer>
</body>
</html>

portfolio/templates/portfolio/login.html
<form action="{% url 'portfolio:login' %}" method="post">
    {% csrf_token %}

    <p>Introduza o seu username: <input type="text" name="username" placeholder="Username"></p>
    <p>Introduza a sua password: <input type="password" name="password" placeholder="Password"></p>

    <input type="submit" value="Entrar!" class="btnSubmit">
</form>

portfolio/templates/portfolio/projetos.html
<!-- projetos.html -->

{% extends 'portfolio/layout.html' %}
{% load static %}
{% block link %}
<link rel="stylesheet" href="{% static 'portfolio/css/estilos.css' %}">
{% endblock %}

{% block main %}
<h1 class="titulo_seccao">Projetos</h1>
    <div class="projects">
        {% for projeto in projetos %}
            <div>
                <h3>{{projeto.titulo}}</h3>
                <br>
                <button><a href="{{projeto.linkgithub}}"><img src="{{projeto.imagem.url}}" width="200"></a></button>
                <br><br>
                <p>{{projeto.descricao}}</p>
                <p><b>Tecnologia(s): </b></p>
                {% for linguagem in projeto.tecnologia.all %}
                <il>{{linguagem}}</il>
                {% endfor %}
                <p><b>Autor(es): </b>{{projeto.participantes}}</p>
                <p><b>UC: </b>{{projeto.cadeira}}</p>
                <p><b>Ano: </b>{{projeto.ano}}</p>
            </div>
        {% endfor %}
    </div>

<h1 class="titulo_seccao">Trabalhos Final de Curso</h1>
    <div class="tfc">
        {% for tfc in tfcs %}
            <div>
                <h3>{{tfc.titulo}}</h3>
                <br>
                <p><b>Autor: </b>{{tfc.autor}}</p>
                {% for orientador in tfc.orientador.all %}
                    <p><b>Orientador: </b>{{orientador.nome}}</p>
                {% endfor %}
                <br>
                <button><a href="{{tfc.linkGitHub}}"><img src="{{tfc.imagem.url}}" width="200"></a></button>
                <br><br>
                <a href="{{tfc.linkYoutube}}"> LinkYoutube</a>
                <br>
                <a href="{{tfc.linkRelatorio}}"> LinkRelatorio</a>
                <br><br>
                <p>{{tfc.sumario}}</p>
                <br>
                <p><b>Ano: </b>{{tfc.ano}}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

portfolio/templates/portfolio/sobre.html
<!-- home.html -->

{% extends 'portfolio/layout.html' %}
{% load static %}
{% block link %}
<link rel="stylesheet" href="{% static 'portfolio/css/estilos.css' %}">
{% endblock %}

{% block main %}
<center><iframe width="700" height="315" src="https://www.youtube.com/embed/Yl_w4WBC-Lk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></center>
    <h1 class="titulo_seccao">Educação</h1>
        <div class="formacao">
            {% for education in educations %}
                        <div>
                            <div class="imagem_formacao">
                                <img src="{{education.imagem.url}}" width="300"></a>
                                <img src="{{education.logotipo.url}}" class="logo" ></a>
                            </div>
                            <h3>{{education.formacao}}</h3>
                            <h4>{{education.curso}} | {{education.periodo}}</h4>
                            <p><b>Local: </b>{{education.local}}</p>
                            <br>
                            <p>{{education.topicos}}</p>
                        </div>
            {% endfor %}
        </div>

    <h1 class="titulo_seccao">Unidades Curriculares</h1>
    <div class="licenciatura">
            {% for chair in chairs %}
                    <div>
                        <h3><u><a href="{{chair.link_cadeira}}" class="titulo">{{chair.nome}}</a></u></h3>
                        <p><b>ECTS: </b>{{chair.ects}}</p>
                        <p><b>Ano: </b>{{chair.ano}}</p>
                        <p><b>Semestre: </b>{{chair.semestre}}</p>
                        <p><b>Ano Letivo: </b> {{chair.ano_letivo}}</p>
                        <p><b>Tópicos abordados: </b>{{chair.topicos_abordados}}</p>
                        <p><b>Linguagens: </b> {% for language in chair.linguagens.all %} {{language.nome}};{% endfor %}</p>
                        <p><b>Ranking (0-5): </b>{{chair.ranking}}</p>
                        <p><b>Docente Teórica: </b><a href="{{chair.docente_teorica.linklusofona}}" class="titulo">{{chair.docente_teorica.nome}}</a></p>
                        <p><b>Docente(s) Práticas: </b> {% for docente_pratica in chair.docentes_praticas.all %}<a href="{{docentes_praticas.linklusofona}}" class="titulo"> {{docente_pratica.nome}}</a> / {% endfor %}</p>
                        <b>Projetos: </b>
                    {% for projeto in chair.projetos.all %}
                        <a href="{% url 'portfolio:projetos' %}" class="titulo">{{projeto.titulo}}</a>; 
                    {% endfor %}
                    </div>
            {% endfor %}
    </div>

    <h1 class="titulo_seccao">Competências</h1>
    <br>
        <div class="competencias">
            <p>O curso de licenciatura em Engenharia Informática da Universidade Lusófona desenvolve
            perfis com fortes competências tecnológicas e humanas, de forma a potênciar aos seus
            licenciados um elevado grau de empregabilidade, ou o prosseguimento dos estudos de 2º ciclo 
            com excelentes perspectivas de sucesso.</p>
        </div>
    <br>
    <h1 class="titulo_seccao">Línguas</h1>
    <div class="linguas1">
        <div class="linguas"> <p><b>Inglês - Língua Nativa</b></p> </div>
        <div class="linguas"> <p><b>Português - B-Preliminary</b></p> </div>
        <div class="linguas"> <p><b>Espanhol - Nível Básico</b></p> </div>
    </div>
    <div class="hobbies">
        <h1 class="titulo_seccao">Hobbies</h1>
        <div class="desportos"> <p><b>Padel</b></p>
        {% load static %}
            <img src="{% static 'portfolio/images/padel.png' %}" width="200">
        </div>
        <div class="desportos"> <p><b>Voluntariado - Gestor de Turno</b></p>
        {% load static %}
            <img src="{% static 'portfolio/images/refood.jpeg' %}" width="200">
        </div>
    </div>
{% endblock %}